/*This program displays all files in current directory
* and adds the files to a list from which copying is to be made
*
*/
#include <dirent.h>
#include <stdio.h>
#include <string.h>
#include <sys/types.h>          /* include necessary header files */
#include <fcntl.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>

#define BUF_SIZE 4096       /* use a buffer size of 4096 bytes */
#define OUTPUT_MODE 0700    /*protection bits for output file */
#define MAX_STR_LEN 256

int main(void){
    DIR *d;
    struct dirent *dir;
    char strTemp[256], srcFile[256], dstFile[256], srcDir[256], dstDir[256];
    char **ptrFileLst;

    char buffer[BUF_SIZE];
    int nrOfStrs=-1, srcFileDesc, dstFileDesc, readByteCount, writeByteCount, numFiles;
    int indPtrFileAcc, q;
    
    float nrFilesCopy;
    //vars for generatingRandNumList
    int i, k, curRanNum, curLstInd, numFound, numsToGen, largNumRange;
    int *numLst;
    //end vars for generating randNumList

    float procFilesCopy;
    printf("Enter name of source Directory\n");
    scanf("%s", srcDir);
    printf("Enter name of destionation Directory\n");
    scanf("%s", dstDir);
    printf("How many files does the directory with mp3 files contain?\n");
    scanf("%d", &numFiles);
    printf("How many percent of the mp3 do you wish to make a random selection of\n");
    printf("enter a number between 1 and 88\n");
    scanf("%f", &procFilesCopy);
    //allocate memory for filesList, list of random numbers
    ptrFileLst= (char**) malloc(numFiles * sizeof(char*));
    for (i=0; i<numFiles; i++)
        ptrFileLst[i] = (char*)malloc(MAX_STR_LEN * sizeof(char));
    largNumRange=numFiles;
    nrFilesCopy=(procFilesCopy/100)*numFiles;
    
    numsToGen=(int)((procFilesCopy/100)*numFiles);
    printf("nrFilesCopy=%f", nrFilesCopy);
    printf("NumsToGen=%d", numsToGen);
    numLst = malloc(numsToGen * sizeof(int));
    srand(time(0));
    
    numLst[0]=rand()%largNumRange+1;
    numFound=0;
    do{
        curRanNum=(int)rand()%largNumRange+1;
        if(numLst[0]==curRanNum){
                numFound=1;
        }
    }while(numFound==1);
    numLst[1]=curRanNum;
    
    getchar();
    curLstInd=1;
    i=0;
    while(1){
        do{
            numFound=0;
            curRanNum=(int)rand()%largNumRange+1;
            for(int k=0; k<=curLstInd; k++){
                if(numLst[k]==curRanNum)
                    numFound=1;
            }
        }while(numFound==1);
        numLst[curLstInd+1]=curRanNum;
        curLstInd++;
        i++;
        //printf("i=%d", i);
        //numsToGen=Totalt numbers to generate minus the two already generated by the code above this loop
        if(i==(numsToGen-2))
            break;
    }

    d = opendir(srcDir);
    if(d){
        while ( (dir = readdir(d)) != NULL  ){
            strcpy(strTemp, dir->d_name);

            if(strTemp[0]!='.'){
                nrOfStrs++;
                strcpy(ptrFileLst[nrOfStrs], strTemp);
            }
        }
        closedir(d);
    }

    for(q=0; q<=curLstInd; q++){
        indPtrFileAcc=numLst[q];
        strcpy(srcFile,srcDir);
        strcat(srcFile, "/");
        strcat(srcFile,ptrFileLst[indPtrFileAcc]);

        strcpy(dstFile,dstDir);
        strcat(dstFile, "/");
        strcat(dstFile,ptrFileLst[indPtrFileAcc]);
        
        srcFileDesc = open(srcFile, O_RDONLY);
        dstFileDesc = creat(dstFile, OUTPUT_MODE);

        while(1){
            readByteCount = read(srcFileDesc, buffer, BUF_SIZE);
            if(readByteCount<=0) 
                break;
            writeByteCount = write(dstFileDesc, buffer, readByteCount);
            if(writeByteCount<=0)
                exit(4);
        }    
        
        //close the files 
        close(srcFileDesc);
        close(dstFileDesc);
    }
}